export const ALBUM_TRACKS = [
  { title: "Rising Above", duration: "3:45" },
  { title: "Breaking the Mould", duration: "4:12" },
  { title: "Samba B", duration: "3:58" },
  { title: "Fake Games", duration: "4:05" },
  { title: "Btz in the House", duration: "3:30" },
  { title: "Love Feels Fake", duration: "4:20" },
  { title: "Tonight", duration: "3:55" },
  { title: "I Found", duration: "4:10" },
  { title: "Action", duration: "3:48" },
  { title: "Shadows in the Rhythm", duration: "4:02" },
  { title: "Flow Do Tigre", duration: "3:00" },
  { title: "Lost in the Secret", duration: "3:33" },
  { title: "Counting My Blessing", duration: "4:01" },
  { title: "Gol", duration: "3:15" },
  { title: "Precision", duration: "3:59" },
  { title: "Alone", duration: "4:21" },
  { title: "Echo of the Soul", duration: "3:50" },
  { title: "Brilho Claro", duration: "3:44" },
  { title: "Tables Turns", duration: "4:08" },
  { title: "The Rain", duration: "3:56" },
];
